# Generated by Django 5.0.6 on 2024-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_geeksmodel_example_age_geeksmodel_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='Ritendra',
            field=models.CharField(default='Ritendra', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='ankit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
