# Generated by Django 5.0.6 on 2024-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_geeksmodel_ritendra_geeksmodel_ankit'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
