# Generated by Django 5.0.6 on 2024-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_geeksmodel_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataApi',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sal', models.FloatField(null=True)),
            ],
        ),
    ]
