# Generated by Django 5.0.6 on 2024-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_dataapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fee', models.IntegerField(null=True)),
            ],
        ),
    ]
