# Generated by Django 5.0.6 on 2024-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('empname', models.CharField(max_length=200)),
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('sal', models.FloatField(null=True)),
            ],
        ),
    ]
